DATASET:
  NAME: "Food101"
  class_descriptor_path: "./descriptors/descriptors_food101_backup.json"
  class_attributes_path: "./imagedistribution_attributes/food-imagedistribution-attributes-GPT3.json"
  class_contexts_path: "./imagedistribution_attributes/food-imagedistribution-contexts-GPT3.json"
  class_embeddings_path: "./imagedistribution_attributes/food/"
  class_captions_path: "./imagedistribution_attributes/food/"
