DATASET:
  NAME: "OxfordPets"
  class_descriptor_path: "./descriptors/descriptors_pets_backup.json"
  class_attributes_path: "./imagedistribution_attributes/pets-imagedistribution-attributes-GPT3.json"
  class_contexts_path: "./imagedistribution_attributes/pets-imagedistribution-contexts-GPT3.json"
  class_embeddings_path: "./imagedistribution_attributes/pets/"
  class_captions_path: "./imagedistribution_attributes/pets/"
